=== chenxuehu2016/seqsvr/xml/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="phxrpc" type="phxrpcType">
        <xs:annotation>
            <xs:documentation>sudo apt install libxml2-utils; xmllint &amp;amp;#45;&amp;amp;#45;noout &amp;amp;#45;&amp;amp;#45;schema schema.xsd dream.xml</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="fieldType">
        <xs:simpleContent>
            <xs:extension base="xs:byte">
                <xs:attribute type="xs:string" name="type" use="required"/>
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="repeated" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="messageType">
        <xs:sequence>
            <xs:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="valueType">
        <xs:simpleContent>
            <xs:extension base="xs:byte">
                <xs:attribute type="xs:string" name="name" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="enumType">
        <xs:sequence>
            <xs:element type="valueType" name="value" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
    </xs:complexType>
    <xs:complexType name="importsType">
        <xs:sequence>
            <xs:element type="xs:string" name="import" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="rpcType">
        <xs:sequence>
            <xs:element type="xs:byte" name="cmdID"/>
            <xs:element type="xs:string" name="optString"/>
            <xs:element type="xs:string" name="usage"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="paramter"/>
        <xs:attribute type="xs:string" name="returns"/>
    </xs:complexType>
    <xs:complexType name="serviceType">
        <xs:sequence>
            <xs:element type="rpcType" name="rpc" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
    <xs:complexType name="phxrpcType">
        <xs:sequence>
            <xs:element type="xs:string" name="package"/>
            <xs:element type="messageType" name="message" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="enumType" name="enum" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="importsType" name="imports" maxOccurs="1" minOccurs="0"/>
            <xs:element type="serviceType" name="service" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== chenxuehu2016/seqsvr/xml/allocsvr.xml
<?xml version="1.0"?>
 <!--sudo apt install libxml2-utils; xmllint &#45;&#45;noout &#45;&#45;schema ../schema.xsd phxbinlogsvr.xml -->
<phxrpc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="./schema.xsd">
    <package>allocsvr</package>
    <message name="SeqReq">
        <field type="uint32" name="uid">1</field>
        <field type="uint32" name="router_ver">2</field>
    </message>
    <message name="SeqResp">
        <field type="uint64" name="seq">1</field>
        <field type="bytes" name="routers">2</field>
    </message>
    <imports>
        <import>google/protobuf/wrappers.proto</import>
        <import>google/protobuf/empty.proto</import>
        <import>phxrpc/rpc/phxrpc.proto</import>
    </imports>
    <service name="phxalloc">
        <rpc name="GetSeq" paramter="SeqReq" returns="SeqResp">
            <cmdID>1</cmdID>
            <optString>u:r:</optString>
            <usage>-u &lt;user&gt; -r &lt;has_router&gt;</usage>
        </rpc>
    </service>
</phxrpc>

=== chenxuehu2016/seqsvr/xml/routerinfo.xml
<?xml version="1.0"?>
 <!--sudo apt install libxml2-utils; xmllint &#45;&#45;noout &#45;&#45;schema ../schema.xsd phxbinlogsvr.xml -->
<phxrpc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="./schema.xsd">
    <package>seqsvr</package>
    <message name="RouterInfo">
        <field type="uint32" name="sect_id">1</field>
        <!-- 标识allocsvr的ip和port -->
        <field type="string" name="alloc_ip">2</field>
        <field type="uint32" name="alloc_port">3</field>

        <!-- 生效时间(秒) -->
        <field type="uint32" name="inure">4</field>
        <!--
       租约失效：AllocSvr N秒内无法从StoreSvr读取加载配置时，AllocSvr停止服务
       租约生效：AllocSvr读取到新的加载配置后，立即卸载需要卸载的号段，需要加载的新号段等待N秒后提供服务
       -->
        <field type="uint32" name="n">5</field>
    </message>

    <message name="RouterList">
        <field type="uint32" name="router_ver">1</field>
        <field type="RouterInfo" repeated="true" name="routers">2</field>
    </message>
    <imports>
        <import>google/protobuf/wrappers.proto</import>
    </imports>
</phxrpc>

=== chenxuehu2016/seqsvr/xml/sectioninfo.xml
<?xml version="1.0"?>
<!--sudo apt install libxml2-utils; xmllint &#45;&#45;noout &#45;&#45;schema ../schema.xsd phxbinlogsvr.xml -->
<phxrpc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="./schema.xsd">
    <package>storesvr</package>
    <message name="SectionInfo">
        <field type="uint32" name="sect_id">1</field>
        <!--  uid号段sect_id => 最大的序列号 -->
        <field type="uint64" name="max_seq">2</field>
    </message>

    <message name="SectionList">
        <field type="SectionInfo" repeated="true" name="sections">1</field>
    </message>
    <imports>
        <import>google/protobuf/wrappers.proto</import>
    </imports>
</phxrpc>
